Zafir changes
TheBookshelf/android pull request #1
Opened 2018-02-25 12:23 UTC by zafir1

2018-02-25 13:01 UTC, rahullama requested changes

2018-02-25 13:01 UTC, rahullama commented on app/src/main/res/layout/splash.xml
> +    >
Remove the spaces.

2018-02-25 13:01 UTC, rahullama commented on app/src/main/res/layout/activity_main.xml
> +<android.support.design.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
Maintain indentation.

2018-02-25 13:01 UTC, rahullama commented on app/src/main/java/in/co/onlinehit/thebookshelf/Splash.java
> +
Remove line 35.

2018-02-27 06:39 UTC, rahullama approved these changes

2018-02-27 06:55 UTC, souravbadami approved these changes

2018-02-27 06:55 UTC, merged